# Generated by Django 5.1.15 on 2026-07-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_game_sport_team_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField()),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_scores', to='games.game')),
            ],
            options={
                'ordering': ['quarter'],
                'unique_together': {('game', 'quarter')},
            },
        ),
    ]
