# Generated by Django 5.1.15 on 2026-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball')], default='football', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball')], default='football', max_length=20),
        ),
    ]
