# Generated by Django 5.1.15 on 2026-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_sport_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
