# Generated by Django 5.1.15 on 2026-07-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('tour', models.CharField(choices=[('atp', 'ATP'), ('wta', 'WTA')], max_length=3)),
                ('ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TennisMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(choices=[('atp', 'ATP'), ('wta', 'WTA')], max_length=3)),
                ('tournament', models.CharField(max_length=100)),
                ('round', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=10)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='tennis.tennisplayer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='tennis.tennisplayer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tennis.tennisplayer')),
            ],
        ),
        migrations.CreateModel(
            name='TennisSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('player1_games', models.PositiveSmallIntegerField()),
                ('player2_games', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tennis.tennismatch')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('match', 'set_number')},
            },
        ),
    ]
