"use client";

import {
  ReactNode,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";

export type Lang = "en" | "he";

const translations = {
  en: {
    tagline: "Pick a sport. Get today's games and AI match analysis.",
    comingSoon: "Coming soon",
    notFoundTitle: "Page not found",
    notFoundBody: "This page doesn't exist, or the link may be broken. Let's get you back on track.",
    goHome: "Go to home",
    errorTitle: "Something went wrong",
    errorBody: "An unexpected error occurred while loading this page. You can try again, or head back home.",
    tryAgain: "Try again",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    navigationMenu: "Navigation menu",
    toggleSidebar: "Toggle sidebar",
    sport_football: "Football",
    sport_basketball: "Basketball",
    sport_tennis: "Tennis",
    otherSports: "Other Sports",
    sport_baseball: "Baseball",
    sport_volleyball: "Volleyball",
    backToSports: "← Sports",
    todaysGames: "Today's Games",
    loadingFixtures: "Loading fixtures...",
    noGames: "No games scheduled today.",
    loadErrorGames: "Couldn't load games",
    loadingMatch: "Loading match...",
    loadErrorGame: "Couldn't load game",
    liveNow: "Live now",
    quarters: "Quarter by Quarter",
    innings: "Inning by Inning",
    sets: "Set by Set",
    form5: "Form (last 5)",
    winsAbbr: "W",
    drawsAbbr: "D",
    lossesAbbr: "L",
    tableTeam: "Team",
    tableGD: "GD",
    tablePts: "Pts",
    tablePlayer: "Player",
    tableCountry: "Country",
    scored: "scored",
    conceded: "conceded",
    lastGames: "last",
    lineups: "Starting Lineups",
    bench: "Bench",
    injuries: "Injuries & Suspensions",
    h2h: "Head to Head",
    noH2h: "No previous meetings on record.",
    draw: "Draw",
    confidence: "Model confidence",
    generatedBy: "Generated by",
    confidence_low: "low",
    confidence_medium: "medium",
    confidence_high: "high",
    injury_out: "out",
    injury_doubtful: "doubtful",
    injury_suspended: "suspended",
    position_gk: "Goalkeeper",
    position_df: "Defender",
    position_mf: "Midfielder",
    position_fw: "Forward",
    home: "Home",
    nav_transfers: "Transfer Center",
    nav_news: "News Center",
    nav_ai_center: "AI Center",
    nav_profile: "Profile",
    nav_settings: "Settings",
    desc_transfers:
      "Real-time transfer rumors, official signings, source credibility ranking, and AI-estimated probabilities — arriving once the Transfer Agent and its data pipeline are built.",
    desc_news:
      "Collected, summarized, and deduplicated sports news — arriving once the News Agent and its data pipeline are built.",
    desc_profile: "Sign in with Google to save favorite teams/players and personalize your feed — arriving once auth is built.",
    desc_settings: "Notification preferences, favorite teams/players, and account settings — arriving alongside the Profile module.",
    signInWithGoogle: "Sign in with Google",
    signOut: "Sign out",
    welcomeBack: "Welcome back",
    profileNote: "Favorites, personalization, and the rest of the Profile module arrive in a later phase — this just proves sign-in works.",
    newsRawNote: "Raw headlines from NewsAPI.org — summarization, dedup clustering, and highlights arrive with the News Agent (Phase 8).",
    newsLoading: "Loading headlines...",
    newsEmpty: "No headlines yet.",
    readMore: "Read more",
    transfersRawNote: "Raw rumors from Transfermarkt — story-grouping/dedup and our own AI-estimated probability arrive with the Transfer Agent (Phase 8). % shown is Transfermarkt's own community assessment.",
    transfersEmpty: "No rumors yet.",
    simulatedDataNote: "Fixtures and scores on this page are simulated for demonstration — not a live real-world schedule.",
    aiCenterIntro: "Ask about any game, team, player, transfer, or general sports question — the Master Agent decides which of the platform's specialist agents to consult and synthesizes one report.",
    aiCenterPlaceholder: "e.g. \"Who's favored in tonight's basketball game?\" or \"Explain the offside rule\"",
    aiCenterSubmit: "Ask",
    aiCenterAsking: "Thinking...",
    aiCenterCached: "Cached answer",
    selectCompetition: "Select a Competition",
    backToCompetitions: "← Competitions",
    tab_live: "Live",
    tab_upcoming: "Upcoming",
    tab_standings: "Standings",
    tab_rankings: "Rankings",
    tab_news: "News",
    tab_transfers: "Transfers",
    tab_ai: "AI Analysis",
    noStandingsData: "No standings data yet for this competition.",
    noRankingsData: "No ranking data yet.",
    noUpcomingGames: "No upcoming games.",
    noLiveGames: "Nothing live right now.",
    // Redesign brief additions —
    heroKicker: "PREMIUM SPORTS PLATFORM",
    heroTitle: "The Future of Sport, Live.",
    heroSubtitle: "Enter a world-class cinematic sports experience across football, basketball, tennis, baseball and volleyball.",
    tagline_football: "Stadiums. Goals. Glory.",
    tagline_basketball: "Courts. Dunks. Drama.",
    tagline_tennis: "Courts. Rallies. Precision.",
    tagline_baseball: "Diamonds. Home Runs. Tension.",
    tagline_volleyball: "Nets. Spikes. Momentum.",
    back: "‹ Back",
    tab_overview: "Overview",
    keyPlayer: "Key Player",
    aiInsightTitle: "AI Match Insight",
    predictionConfidence: "Prediction confidence",
    winProbabilities: "Win probabilities",
    playerPhoto: "PLAYER PHOTO",
    language: "Language",
    appearance: "Appearance",
    cinematic: "Cinematic",
    focus: "Focus",
    notifications: "Match Notifications",
    notificationsHint: "Get alerts for live scoring plays and score changes.",
    stat_possession: "Possession",
    stat_shots: "Shots",
    stat_shotsOnTarget: "Shots on Target",
    stat_corners: "Corners",
    stat_points: "Points",
    stat_rebounds: "Rebounds",
    stat_assists: "Assists",
    stat_fgPct: "FG%",
    stat_aces: "Aces",
    stat_winners: "Winners",
    stat_unforcedErrors: "Unforced Errors",
    stat_doubleFaults: "Double Faults",
    stat_hits: "Hits",
    stat_runs: "Runs",
    stat_errors: "Errors",
    stat_walks: "Walks",
    stat_kills: "Kills",
    stat_digs: "Digs",
    stat_blocks: "Blocks",
    playerGoals: "Goals",
    playerAssists: "Assists",
    playerRating: "Rating",
    playerPpg: "PPG",
    playerRpg: "RPG",
    playerApg: "APG",
    playerWorldRank: "World Rank",
    playerWinPct: "Win %",
    playerAcesPerMatch: "Aces/Match",
    playerAvg: "AVG",
    playerHomeRuns: "HR",
    playerRbi: "RBI",
    playerKills: "Kills/Set",
    playerDigs: "Digs/Set",
    playerBlocks: "Blocks/Set",
    statusFinished: "Full Time",
    tourAtp: "ATP Tour",
    tourWta: "WTA Tour",
    positionSingles: "Singles",
    matches: "matches",
    tab_matchEvents: "Match Events",
    event_goal: "Goal",
    event_penalty_goal: "Penalty",
    event_own_goal: "Own Goal",
    event_yellow_card: "Yellow Card",
    event_red_card: "Red Card",
    event_substitution: "Substitution",
    event_var_review: "VAR Review",
    noMatchEvents: "No match events yet.",
    transferStatus_rumor: "Rumor",
    transferStatus_official: "Official",
    transferStatus_completed: "Completed",
    transferStatus_denied: "Denied",
    squad: "Squad",
    coach: "Coach",
    verifiedPlayer: "Verified",
    noRosterData: "No squad data yet for this team.",
    simulatedBadge: "Demo Season",
  },
  he: {
    tagline: "בוחרים ענף ספורט, מקבלים את משחקי היום וניתוח AI לכל משחק.",
    comingSoon: "בקרוב",
    notFoundTitle: "העמוד לא נמצא",
    notFoundBody: "נראה שהעמוד הזה לא קיים, או שהקישור שגוי. בואו נחזיר אתכם למסלול.",
    goHome: "חזרה לדף הבית",
    errorTitle: "משהו השתבש",
    errorBody: "קרתה תקלה בלתי צפויה בטעינת העמוד. אפשר לנסות שוב, או לחזור לדף הבית.",
    tryAgain: "ניסיון נוסף",
    openMenu: "פתיחת תפריט",
    closeMenu: "סגירת תפריט",
    navigationMenu: "תפריט ניווט",
    toggleSidebar: "כיווץ/הרחבת סרגל ניווט",
    sport_football: "כדורגל",
    sport_basketball: "כדורסל",
    sport_tennis: "טניס",
    otherSports: "ענפי ספורט נוספים",
    sport_baseball: "בייסבול",
    sport_volleyball: "כדורעף",
    backToSports: "→ ענפי ספורט",
    todaysGames: "משחקי היום",
    loadingFixtures: "טוען משחקים...",
    noGames: "אין משחקים מתוכננים היום.",
    loadErrorGames: "לא ניתן לטעון את המשחקים",
    loadingMatch: "טוען משחק...",
    loadErrorGame: "לא ניתן לטעון את המשחק",
    liveNow: "בשידור חי",
    quarters: "רבעים",
    innings: "אינינגים",
    sets: "סטים",
    form5: "כושר (5 אחרונים)",
    winsAbbr: "נ",
    drawsAbbr: "ת",
    lossesAbbr: "ה",
    tableTeam: "קבוצה",
    tableGD: "הפרש",
    tablePts: "נק'",
    tablePlayer: "שחקן",
    tableCountry: "מדינה",
    scored: "לזכות",
    conceded: "לחובה",
    lastGames: "ב־",
    lineups: "הרכבים",
    bench: "ספסל",
    injuries: "פציעות והרחקות",
    h2h: "מפגשים קודמים",
    noH2h: "אין מפגשים קודמים.",
    draw: "תיקו",
    confidence: "רמת ביטחון של המודל",
    generatedBy: "נוצר על ידי",
    confidence_low: "נמוכה",
    confidence_medium: "בינונית",
    confidence_high: "גבוהה",
    injury_out: "לא ישחק",
    injury_doubtful: "מוטל בספק",
    injury_suspended: "מורחק",
    position_gk: "שוער",
    position_df: "מגן",
    position_mf: "קשר",
    position_fw: "חלוץ",
    home: "בית",
    nav_transfers: "מרכז מעברים",
    nav_news: "מרכז חדשות",
    nav_ai_center: "מרכז AI",
    nav_profile: "פרופיל",
    nav_settings: "הגדרות",
    desc_transfers:
      "שמועות מעברים בזמן אמת, חתימות רשמיות, דירוג אמינות מקורות והסתברויות המבוססות על AI — בקרוב, לאחר בניית סוכן המעברים וצינור הנתונים שלו.",
    desc_news: "חדשות ספורט שנאספות, מסוכמות ומנוקות מכפילויות — בקרוב, לאחר בניית סוכן החדשות וצינור הנתונים שלו.",
    desc_profile: "התחברות עם Google לשמירת קבוצות/שחקנים מועדפים והתאמה אישית של הפיד — בקרוב, לאחר בניית מערכת ההתחברות.",
    desc_settings: "העדפות התראות, קבוצות/שחקנים מועדפים והגדרות חשבון — בקרוב, יחד עם מודול הפרופיל.",
    signInWithGoogle: "התחברות עם Google",
    signOut: "התנתקות",
    welcomeBack: "ברוך שובך",
    profileNote: "מועדפים, התאמה אישית ושאר מודול הפרופיל יגיעו בשלב מאוחר יותר — זה רק מוכיח שההתחברות עובדת.",
    newsRawNote: "כותרות גולמיות מ-NewsAPI.org — סיכום, איתור כפילויות והדגשות יגיעו עם סוכן החדשות (שלב 8).",
    newsLoading: "טוען כותרות...",
    newsEmpty: "אין כותרות עדיין.",
    readMore: "קרא עוד",
    transfersRawNote: "שמועות גולמיות מ-Transfermarkt — קיבוץ סיפורים/ניקוי כפילויות והסתברות משוערת משלנו יגיעו עם סוכן המעברים (שלב 8). האחוז המוצג הוא הערכת הקהילה של Transfermarkt עצמה.",
    transfersEmpty: "אין שמועות עדיין.",
    simulatedDataNote: "המשחקים והתוצאות בעמוד זה מדומים להדגמה בלבד — אינם לוח משחקים אמיתי בזמן אמת.",
    aiCenterIntro: "שאלו על כל משחק, קבוצה, שחקן, מעבר, או כל שאלת ספורט כללית — הסוכן הראשי מחליט באילו סוכני AI מומחים להיעזר ומסנתז דוח אחד.",
    aiCenterPlaceholder: "לדוגמה: \"מי מועדף במשחק הכדורסל הערב?\" או \"הסבירו לי את חוק הנבדל\"",
    aiCenterSubmit: "שאל",
    aiCenterAsking: "חושב...",
    aiCenterCached: "תשובה שמורה",
    selectCompetition: "בחר תחרות",
    backToCompetitions: "→ תחרויות",
    tab_live: "בשידור חי",
    tab_upcoming: "משחקים קרובים",
    tab_standings: "טבלה",
    tab_rankings: "דירוג",
    tab_news: "חדשות",
    tab_transfers: "מעברים",
    tab_ai: "ניתוח AI",
    noStandingsData: "אין עדיין נתוני טבלה לתחרות זו.",
    noRankingsData: "אין עדיין נתוני דירוג.",
    noUpcomingGames: "אין משחקים קרובים.",
    noLiveGames: "אין כרגע שידורים חיים.",
    // Redesign brief additions —
    heroKicker: "פלטפורמת ספורט פרימיום",
    heroTitle: "עתיד הספורט, בשידור חי.",
    heroSubtitle: "היכנסו לחוויית ספורט קולנועית ברמה עולמית — כדורגל, כדורסל, טניס, בייסבול וכדורעף.",
    tagline_football: "אצטדיונים. שערים. תהילה.",
    tagline_basketball: "מגרשים. סלאמים. דרמה.",
    tagline_tennis: "מגרשים. חילופים. דיוק.",
    tagline_baseball: "בסיסים. הומראנים. מתח.",
    tagline_volleyball: "רשתות. חבטות. תנופה.",
    back: "חזרה ›",
    tab_overview: "סקירה",
    keyPlayer: "שחקן מפתח",
    aiInsightTitle: "תובנת AI למשחק",
    predictionConfidence: "רמת ביטחון בחיזוי",
    winProbabilities: "סיכויי ניצחון",
    playerPhoto: "תמונת שחקן",
    language: "שפה",
    appearance: "מראה",
    cinematic: "קולנועי",
    focus: "פוקוס",
    notifications: "התראות משחק",
    notificationsHint: "קבלו התראות על אירועי ניקוד ושינויי תוצאה בזמן אמת.",
    stat_possession: "נתח בעלות",
    stat_shots: "בעיטות",
    stat_shotsOnTarget: "בעיטות למסגרת",
    stat_corners: "קרנות",
    stat_points: "נקודות",
    stat_rebounds: "ריבאונדים",
    stat_assists: "אסיסטים",
    stat_fgPct: "אחוז קליעה",
    stat_aces: "אייסים",
    stat_winners: "מכות ניצחון",
    stat_unforcedErrors: "טעויות לא כפויות",
    stat_doubleFaults: "טעויות כפולות",
    stat_hits: "פגיעות",
    stat_runs: "ריצות",
    stat_errors: "שגיאות",
    stat_walks: "בסיס על כדורים",
    stat_kills: "חבטות",
    stat_digs: "הצלות",
    stat_blocks: "חסימות",
    playerGoals: "שערים",
    playerAssists: "בישולים",
    playerRating: "דירוג",
    playerPpg: "ממוצע נק'",
    playerRpg: "ריבאונדים",
    playerApg: "אסיסטים",
    playerWorldRank: "דירוג עולמי",
    playerWinPct: "אחוז ניצחונות",
    playerAcesPerMatch: "אייסים/משחק",
    playerAvg: "ממוצע חביטה",
    playerHomeRuns: "הומראנים",
    playerRbi: "ריצות מובאות",
    playerKills: "חבטות/סט",
    playerDigs: "הצלות/סט",
    playerBlocks: "חסימות/סט",
    statusFinished: "סיום",
    tourAtp: "טור ATP",
    tourWta: "טור WTA",
    positionSingles: "יחידים",
    matches: "משחקים",
    tab_matchEvents: "אירועי משחק",
    event_goal: "שער",
    event_penalty_goal: "פנדל",
    event_own_goal: "שער עצמי",
    event_yellow_card: "כרטיס צהוב",
    event_red_card: "כרטיס אדום",
    event_substitution: "חילוף",
    event_var_review: "בדיקת VAR",
    noMatchEvents: "אין עדיין אירועי משחק.",
    transferStatus_rumor: "שמועה",
    transferStatus_official: "העברה רשמית",
    transferStatus_completed: "הושלמה",
    transferStatus_denied: "נדחתה",
    squad: "סגל",
    coach: "מאמן",
    verifiedPlayer: "מאומת",
    noRosterData: "אין עדיין נתוני סגל לקבוצה זו.",
    simulatedBadge: "עונת דמו",
  },
} as const;

export type TKey = keyof (typeof translations)["en"];

// Football's Player.position values (see prisma/schema.prisma) are the
// short GK/DF/MF/FW codes this app normalizes every source onto (both the
// fictional seed data and the real football-data.org squad enrichment,
// see prisma/enrich-football-data-squads.ts) — translated via the
// position_gk/df/mf/fw keys above. Named `...Football...` (not the more
// generic `translatePosition`) since basketball's own PG/SG/SF/PF/C-style
// codes are a separate, differently-shaped lookup (see lib/positions.ts)
// — deliberately not unified with this one to avoid two concurrently
// written position-translation helpers colliding on one name/module. Any
// other sport's position code — or an unrecognized value — passes through
// unchanged, same "untranslated original" fallback as
// translations/fields.py's TranslatedCharField on the backend.
const TRANSLATABLE_FOOTBALL_POSITION_CODES = new Set(["gk", "df", "mf", "fw"]);

export function translateFootballPosition(t: (key: TKey) => string, position: string): string {
  const code = position.toLowerCase();
  if (!TRANSLATABLE_FOOTBALL_POSITION_CODES.has(code)) return position;
  return t(`position_${code}` as TKey);
}

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TKey) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "he",
  setLang: () => {},
  t: (key) => translations.he[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Defaults to "he" on BOTH server and first client render — reading
  // localStorage inside the initializer (the previous approach) computes
  // "en" on the client's very first render whenever a returning user has
  // that persisted, which never matches the server-rendered "he" HTML and
  // triggers a full hydration-mismatch/client-re-render. A real, concrete
  // instance of this was hit once a component's first render started
  // depending on `lang` for something more than translated text (the
  // sidebar's collapse-chevron direction) — text mismatches degrade
  // gracefully, but a differing SVG path attribute doesn't. The persisted
  // value is applied in a useEffect after mount instead, same fix pattern
  // used in lib/sidebar-state.tsx.
  const [lang, setLang] = useState<Lang>("he");

  useEffect(() => {
    const stored = window.localStorage.getItem("lang");
    if (stored === "en") setLang("en");
  }, []);

  useEffect(() => {
    localStorage.setItem("lang", lang);
    // Mirrored into a cookie (readable by the server layout, unlike
    // localStorage) so the *next* request's SSR <html lang/dir> already
    // matches this tab's language — same "persist past the fix" pattern as
    // the localStorage write above, just for the server-rendered attributes.
    document.cookie = `lang=${lang}; path=/; max-age=31536000; samesite=lax`;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "he" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: TKey) => translations[lang][key] ?? translations.en[key];

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);

// Segmented two-option pill (EN / עב), active option filled with the brand
// accent gradient — matches the design brief's language toggle exactly,
// replacing the old single-button "switch to the other language" control.
export function LangToggle() {
  const { lang, setLang } = useLang();
  const options: { key: Lang; label: string }[] = [
    { key: "en", label: "EN" },
    { key: "he", label: "עב" },
  ];
  return (
    <div className="inline-flex gap-0.5 rounded-full border border-white/10 bg-white/5 p-0.5">
      {options.map((opt) => {
        const active = lang === opt.key;
        return (
          <button
            key={opt.key}
            type="button"
            onClick={() => setLang(opt.key)}
            aria-label={`Switch to ${opt.label}`}
            aria-pressed={active}
            className={
              active
                ? "rounded-full bg-[linear-gradient(135deg,var(--brand-accent),var(--brand-accent-2))] px-3 py-1 text-xs font-bold text-[#06121c]"
                : "rounded-full px-3 py-1 text-xs font-semibold text-white/60 transition hover:text-white"
            }
          >
            {opt.label}
          </button>
        );
      })}
    </div>
  );
}
