"use client";

import {
  ReactNode,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";

export type Lang = "en" | "he";

const translations = {
  en: {
    tagline: "Pick a sport. Get today's games and AI match analysis.",
    comingSoon: "Coming soon",
    sport_football: "Football",
    sport_basketball: "Basketball",
    sport_tennis: "Tennis",
    otherSports: "Other Sports",
    sport_baseball: "Baseball",
    sport_volleyball: "Volleyball",
    backToSports: "← Sports",
    todaysGames: "Today's Games",
    loadingFixtures: "Loading fixtures...",
    noGames: "No games scheduled today.",
    loadErrorGames: "Couldn't load games",
    backToGames: "← Today's games",
    loadingMatch: "Loading match...",
    loadErrorGame: "Couldn't load game",
    aiAnalysis: "🤖 AI Match Analysis",
    analyzing: "The AI Agent is analyzing this match…",
    liveNow: "Live now",
    quarters: "Quarter by Quarter",
    form5: "Form (last 5)",
    winsAbbr: "W",
    drawsAbbr: "D",
    lossesAbbr: "L",
    scored: "scored",
    conceded: "conceded",
    lastGames: "last",
    lineups: "Starting Lineups",
    bench: "Bench",
    injuries: "Injuries & Suspensions",
    h2h: "Head to Head",
    noH2h: "No previous meetings on record.",
    draw: "Draw",
    confidence: "Confidence",
    generatedBy: "Generated by",
    confidence_low: "low",
    confidence_medium: "medium",
    confidence_high: "high",
    injury_out: "out",
    injury_doubtful: "doubtful",
    injury_suspended: "suspended",
    home: "Home",
    nav_transfers: "Transfer Center",
    nav_news: "News Center",
    nav_ai_center: "AI Center",
    nav_profile: "Profile",
    nav_settings: "Settings",
    desc_transfers:
      "Real-time transfer rumors, official signings, source credibility ranking, and AI-estimated probabilities — arriving once the Transfer Agent and its data pipeline are built.",
    desc_news:
      "Collected, summarized, and deduplicated sports news — arriving once the News Agent and its data pipeline are built.",
    desc_ai_center:
      "A unified view across every AI agent — Football, Basketball, Tennis, Transfer, Statistics, News, Prediction — synthesized by a Master Agent into one coherent report.",
    desc_profile: "Sign in with Google to save favorite teams/players and personalize your feed — arriving once auth is built.",
    desc_settings: "Notification preferences, favorite teams/players, and account settings — arriving alongside the Profile module.",
    signInWithGoogle: "Sign in with Google",
    signOut: "Sign out",
    welcomeBack: "Welcome back",
    profileNote: "Favorites, personalization, and the rest of the Profile module arrive in a later phase — this just proves sign-in works.",
    newsRawNote: "Raw headlines from NewsAPI.org — summarization, dedup clustering, and highlights arrive with the News Agent (Phase 8).",
    newsLoading: "Loading headlines...",
    newsEmpty: "No headlines yet.",
    readMore: "Read more",
  },
  he: {
    tagline: "בוחרים ענף ספורט, מקבלים את משחקי היום וניתוח AI לכל משחק.",
    comingSoon: "בקרוב",
    sport_football: "כדורגל",
    sport_basketball: "כדורסל",
    sport_tennis: "טניס",
    otherSports: "ענפי ספורט נוספים",
    sport_baseball: "בייסבול",
    sport_volleyball: "כדורעף",
    backToSports: "→ ענפי ספורט",
    todaysGames: "משחקי היום",
    loadingFixtures: "טוען משחקים...",
    noGames: "אין משחקים מתוכננים היום.",
    loadErrorGames: "לא ניתן לטעון את המשחקים",
    backToGames: "→ משחקי היום",
    loadingMatch: "טוען משחק...",
    loadErrorGame: "לא ניתן לטעון את המשחק",
    aiAnalysis: "🤖 ניתוח AI למשחק",
    analyzing: "סוכן ה-AI מנתח את המשחק…",
    liveNow: "בשידור חי",
    quarters: "רבעים",
    form5: "כושר (5 אחרונים)",
    winsAbbr: "נ",
    drawsAbbr: "ת",
    lossesAbbr: "ה",
    scored: "שערי זכות",
    conceded: "שערי חובה",
    lastGames: "ב־",
    lineups: "הרכבים",
    bench: "ספסל",
    injuries: "פציעות והרחקות",
    h2h: "מפגשים קודמים",
    noH2h: "אין מפגשים קודמים.",
    draw: "תיקו",
    confidence: "רמת ביטחון",
    generatedBy: "נוצר על ידי",
    confidence_low: "נמוכה",
    confidence_medium: "בינונית",
    confidence_high: "גבוהה",
    injury_out: "לא ישחק",
    injury_doubtful: "מוטל בספק",
    injury_suspended: "מורחק",
    home: "בית",
    nav_transfers: "מרכז מעברים",
    nav_news: "מרכז חדשות",
    nav_ai_center: "מרכז AI",
    nav_profile: "פרופיל",
    nav_settings: "הגדרות",
    desc_transfers:
      "שמועות מעברים בזמן אמת, חתימות רשמיות, דירוג אמינות מקורות והסתברויות המבוססות על AI — בקרוב, לאחר בניית סוכן המעברים וצינור הנתונים שלו.",
    desc_news: "חדשות ספורט שנאספות, מסוכמות ומנוקות מכפילויות — בקרוב, לאחר בניית סוכן החדשות וצינור הנתונים שלו.",
    desc_ai_center:
      "תצוגה מאוחדת של כל סוכני ה-AI — כדורגל, כדורסל, טניס, מעברים, סטטיסטיקה, חדשות, חיזויים — מסונתזת על ידי סוכן ראשי לדוח אחד קוהרנטי.",
    desc_profile: "התחברות עם Google לשמירת קבוצות/שחקנים מועדפים והתאמה אישית של הפיד — בקרוב, לאחר בניית מערכת ההתחברות.",
    desc_settings: "העדפות התראות, קבוצות/שחקנים מועדפים והגדרות חשבון — בקרוב, יחד עם מודול הפרופיל.",
    signInWithGoogle: "התחברות עם Google",
    signOut: "התנתקות",
    welcomeBack: "ברוך שובך",
    profileNote: "מועדפים, התאמה אישית ושאר מודול הפרופיל יגיעו בשלב מאוחר יותר — זה רק מוכיח שההתחברות עובדת.",
    newsRawNote: "כותרות גולמיות מ-NewsAPI.org — סיכום, איתור כפילויות והדגשות יגיעו עם סוכן החדשות (שלב 8).",
    newsLoading: "טוען כותרות...",
    newsEmpty: "אין כותרות עדיין.",
    readMore: "קרא עוד",
  },
} as const;

export type TKey = keyof (typeof translations)["en"];

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TKey) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "he",
  setLang: () => {},
  t: (key) => translations.he[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    if (typeof window === "undefined") return "he";
    const stored = window.localStorage.getItem("lang");
    return stored === "en" ? "en" : "he";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "he" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: TKey) => translations[lang][key] ?? translations.en[key];

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);

export function LangToggle() {
  const { lang, setLang } = useLang();
  return (
    <button
      className="rounded-full bg-white/10 px-3 py-1 text-sm text-white transition hover:bg-white/20"
      onClick={() => setLang(lang === "en" ? "he" : "en")}
      aria-label="Switch language"
    >
      {lang === "en" ? "עברית" : "English"}
    </button>
  );
}
