"use client";

import {
  ReactNode,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";

export type Lang = "en" | "he";

const translations = {
  en: {
    tagline: "Pick a sport. Get today's games and AI match analysis.",
    comingSoon: "Coming soon",
    sport_football: "Football",
    sport_basketball: "Basketball",
    sport_tennis: "Tennis",
    otherSports: "Other Sports",
    sport_baseball: "Baseball",
    sport_volleyball: "Volleyball",
    backToSports: "← Sports",
    todaysGames: "Today's Games",
    loadingFixtures: "Loading fixtures...",
    noGames: "No games scheduled today.",
    loadErrorGames: "Couldn't load games",
    loadingMatch: "Loading match...",
    loadErrorGame: "Couldn't load game",
    liveNow: "Live now",
    quarters: "Quarter by Quarter",
    form5: "Form (last 5)",
    winsAbbr: "W",
    drawsAbbr: "D",
    lossesAbbr: "L",
    scored: "scored",
    conceded: "conceded",
    lastGames: "last",
    lineups: "Starting Lineups",
    bench: "Bench",
    injuries: "Injuries & Suspensions",
    h2h: "Head to Head",
    noH2h: "No previous meetings on record.",
    draw: "Draw",
    confidence: "Confidence",
    generatedBy: "Generated by",
    confidence_low: "low",
    confidence_medium: "medium",
    confidence_high: "high",
    injury_out: "out",
    injury_doubtful: "doubtful",
    injury_suspended: "suspended",
    home: "Home",
    nav_transfers: "Transfer Center",
    nav_news: "News Center",
    nav_ai_center: "AI Center",
    nav_profile: "Profile",
    nav_settings: "Settings",
    desc_transfers:
      "Real-time transfer rumors, official signings, source credibility ranking, and AI-estimated probabilities — arriving once the Transfer Agent and its data pipeline are built.",
    desc_news:
      "Collected, summarized, and deduplicated sports news — arriving once the News Agent and its data pipeline are built.",
    desc_ai_center:
      "A unified view across every AI agent — Football, Basketball, Tennis, Transfer, Statistics, News, Prediction — synthesized by a Master Agent into one coherent report.",
    desc_profile: "Sign in with Google to save favorite teams/players and personalize your feed — arriving once auth is built.",
    desc_settings: "Notification preferences, favorite teams/players, and account settings — arriving alongside the Profile module.",
    signInWithGoogle: "Sign in with Google",
    signOut: "Sign out",
    welcomeBack: "Welcome back",
    profileNote: "Favorites, personalization, and the rest of the Profile module arrive in a later phase — this just proves sign-in works.",
    newsRawNote: "Raw headlines from NewsAPI.org — summarization, dedup clustering, and highlights arrive with the News Agent (Phase 8).",
    newsLoading: "Loading headlines...",
    newsEmpty: "No headlines yet.",
    readMore: "Read more",
    transfersRawNote: "Raw rumors from Transfermarkt — story-grouping/dedup and our own AI-estimated probability arrive with the Transfer Agent (Phase 8). % shown is Transfermarkt's own community assessment.",
    transfersEmpty: "No rumors yet.",
    selectCompetition: "Select a Competition",
    backToCompetitions: "← Competitions",
    tab_live: "Live",
    tab_upcoming: "Upcoming",
    tab_standings: "Standings",
    tab_rankings: "Rankings",
    tab_news: "News",
    tab_transfers: "Transfers",
    tab_ai: "AI Analysis",
    noStandingsData: "No standings data yet for this competition.",
    noRankingsData: "No ranking data yet.",
    noUpcomingGames: "No upcoming games.",
    noLiveGames: "Nothing live right now.",
    // Redesign brief additions —
    heroKicker: "PREMIUM SPORTS PLATFORM",
    heroTitle: "The Future of Sport, Live.",
    heroSubtitle: "Enter a world-class cinematic sports experience across football, basketball and tennis.",
    tagline_football: "Stadiums. Goals. Glory.",
    tagline_basketball: "Courts. Dunks. Drama.",
    tagline_tennis: "Courts. Rallies. Precision.",
    back: "‹ Back",
    tab_overview: "Overview",
    keyPlayer: "Key Player",
    aiInsightTitle: "AI Match Insight",
    predictionConfidence: "Prediction confidence",
    playerPhoto: "PLAYER PHOTO",
    language: "Language",
    appearance: "Appearance",
    cinematic: "Cinematic",
    focus: "Focus",
    notifications: "Match Notifications",
    notificationsHint: "Get alerts for live goals and score changes.",
    stat_possession: "Possession",
    stat_shots: "Shots",
    stat_shotsOnTarget: "Shots on Target",
    stat_corners: "Corners",
    stat_points: "Points",
    stat_rebounds: "Rebounds",
    stat_assists: "Assists",
    stat_fgPct: "FG%",
    stat_aces: "Aces",
    stat_winners: "Winners",
    stat_unforcedErrors: "Unforced Errors",
    stat_doubleFaults: "Double Faults",
    playerGoals: "Goals",
    playerAssists: "Assists",
    playerRating: "Rating",
    playerPpg: "PPG",
    playerRpg: "RPG",
    playerApg: "APG",
    playerWorldRank: "World Rank",
    playerWinPct: "Win %",
    playerAcesPerMatch: "Aces/Match",
    statusFinished: "Full Time",
    tourAtp: "ATP Tour",
    tourWta: "WTA Tour",
    positionSingles: "Singles",
  },
  he: {
    tagline: "בוחרים ענף ספורט, מקבלים את משחקי היום וניתוח AI לכל משחק.",
    comingSoon: "בקרוב",
    sport_football: "כדורגל",
    sport_basketball: "כדורסל",
    sport_tennis: "טניס",
    otherSports: "ענפי ספורט נוספים",
    sport_baseball: "בייסבול",
    sport_volleyball: "כדורעף",
    backToSports: "→ ענפי ספורט",
    todaysGames: "משחקי היום",
    loadingFixtures: "טוען משחקים...",
    noGames: "אין משחקים מתוכננים היום.",
    loadErrorGames: "לא ניתן לטעון את המשחקים",
    loadingMatch: "טוען משחק...",
    loadErrorGame: "לא ניתן לטעון את המשחק",
    liveNow: "בשידור חי",
    quarters: "רבעים",
    form5: "כושר (5 אחרונים)",
    winsAbbr: "נ",
    drawsAbbr: "ת",
    lossesAbbr: "ה",
    scored: "שערי זכות",
    conceded: "שערי חובה",
    lastGames: "ב־",
    lineups: "הרכבים",
    bench: "ספסל",
    injuries: "פציעות והרחקות",
    h2h: "מפגשים קודמים",
    noH2h: "אין מפגשים קודמים.",
    draw: "תיקו",
    confidence: "רמת ביטחון",
    generatedBy: "נוצר על ידי",
    confidence_low: "נמוכה",
    confidence_medium: "בינונית",
    confidence_high: "גבוהה",
    injury_out: "לא ישחק",
    injury_doubtful: "מוטל בספק",
    injury_suspended: "מורחק",
    home: "בית",
    nav_transfers: "מרכז מעברים",
    nav_news: "מרכז חדשות",
    nav_ai_center: "מרכז AI",
    nav_profile: "פרופיל",
    nav_settings: "הגדרות",
    desc_transfers:
      "שמועות מעברים בזמן אמת, חתימות רשמיות, דירוג אמינות מקורות והסתברויות המבוססות על AI — בקרוב, לאחר בניית סוכן המעברים וצינור הנתונים שלו.",
    desc_news: "חדשות ספורט שנאספות, מסוכמות ומנוקות מכפילויות — בקרוב, לאחר בניית סוכן החדשות וצינור הנתונים שלו.",
    desc_ai_center:
      "תצוגה מאוחדת של כל סוכני ה-AI — כדורגל, כדורסל, טניס, מעברים, סטטיסטיקה, חדשות, חיזויים — מסונתזת על ידי סוכן ראשי לדוח אחד קוהרנטי.",
    desc_profile: "התחברות עם Google לשמירת קבוצות/שחקנים מועדפים והתאמה אישית של הפיד — בקרוב, לאחר בניית מערכת ההתחברות.",
    desc_settings: "העדפות התראות, קבוצות/שחקנים מועדפים והגדרות חשבון — בקרוב, יחד עם מודול הפרופיל.",
    signInWithGoogle: "התחברות עם Google",
    signOut: "התנתקות",
    welcomeBack: "ברוך שובך",
    profileNote: "מועדפים, התאמה אישית ושאר מודול הפרופיל יגיעו בשלב מאוחר יותר — זה רק מוכיח שההתחברות עובדת.",
    newsRawNote: "כותרות גולמיות מ-NewsAPI.org — סיכום, איתור כפילויות והדגשות יגיעו עם סוכן החדשות (שלב 8).",
    newsLoading: "טוען כותרות...",
    newsEmpty: "אין כותרות עדיין.",
    readMore: "קרא עוד",
    transfersRawNote: "שמועות גולמיות מ-Transfermarkt — קיבוץ סיפורים/ניקוי כפילויות והסתברות משוערת משלנו יגיעו עם סוכן המעברים (שלב 8). האחוז המוצג הוא הערכת הקהילה של Transfermarkt עצמה.",
    transfersEmpty: "אין שמועות עדיין.",
    selectCompetition: "בחר תחרות",
    backToCompetitions: "→ תחרויות",
    tab_live: "בשידור חי",
    tab_upcoming: "משחקים קרובים",
    tab_standings: "טבלה",
    tab_rankings: "דירוג",
    tab_news: "חדשות",
    tab_transfers: "מעברים",
    tab_ai: "ניתוח AI",
    noStandingsData: "אין עדיין נתוני טבלה לתחרות זו.",
    noRankingsData: "אין עדיין נתוני דירוג.",
    noUpcomingGames: "אין משחקים קרובים.",
    noLiveGames: "אין כרגע שידורים חיים.",
    // Redesign brief additions —
    heroKicker: "פלטפורמת ספורט פרימיום",
    heroTitle: "עתיד הספורט, בשידור חי.",
    heroSubtitle: "היכנסו לחוויית ספורט קולנועית ברמה עולמית — כדורגל, כדורסל וטניס.",
    tagline_football: "אצטדיונים. שערים. תהילה.",
    tagline_basketball: "מגרשים. סלאמים. דרמה.",
    tagline_tennis: "מגרשים. חילופים. דיוק.",
    back: "חזרה ›",
    tab_overview: "סקירה",
    keyPlayer: "שחקן מפתח",
    aiInsightTitle: "תובנת AI למשחק",
    predictionConfidence: "רמת ביטחון בחיזוי",
    playerPhoto: "תמונת שחקן",
    language: "שפה",
    appearance: "מראה",
    cinematic: "קולנועי",
    focus: "פוקוס",
    notifications: "התראות משחק",
    notificationsHint: "קבלו התראות על שערים ושינויי תוצאה בזמן אמת.",
    stat_possession: "נתח בעלות",
    stat_shots: "בעיטות",
    stat_shotsOnTarget: "בעיטות למסגרת",
    stat_corners: "קרנות",
    stat_points: "נקודות",
    stat_rebounds: "ריבאונדים",
    stat_assists: "אסיסטים",
    stat_fgPct: "אחוז קליעה",
    stat_aces: "אייסים",
    stat_winners: "זכיות",
    stat_unforcedErrors: "טעויות לא כפויות",
    stat_doubleFaults: "כפולות טעות",
    playerGoals: "שערים",
    playerAssists: "בישולים",
    playerRating: "דירוג",
    playerPpg: "ממוצע נק'",
    playerRpg: "ריבאונדים",
    playerApg: "אסיסטים",
    playerWorldRank: "דירוג עולמי",
    playerWinPct: "אחוז ניצחונות",
    playerAcesPerMatch: "אייסים/משחק",
    statusFinished: "סיום",
    tourAtp: "טור ATP",
    tourWta: "טור WTA",
    positionSingles: "יחידים",
  },
} as const;

export type TKey = keyof (typeof translations)["en"];

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TKey) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "he",
  setLang: () => {},
  t: (key) => translations.he[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Defaults to "he" on BOTH server and first client render — reading
  // localStorage inside the initializer (the previous approach) computes
  // "en" on the client's very first render whenever a returning user has
  // that persisted, which never matches the server-rendered "he" HTML and
  // triggers a full hydration-mismatch/client-re-render. A real, concrete
  // instance of this was hit once a component's first render started
  // depending on `lang` for something more than translated text (the
  // sidebar's collapse-chevron direction) — text mismatches degrade
  // gracefully, but a differing SVG path attribute doesn't. The persisted
  // value is applied in a useEffect after mount instead, same fix pattern
  // used in lib/sidebar-state.tsx.
  const [lang, setLang] = useState<Lang>("he");

  useEffect(() => {
    const stored = window.localStorage.getItem("lang");
    if (stored === "en") setLang("en");
  }, []);

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "he" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: TKey) => translations[lang][key] ?? translations.en[key];

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);

// Segmented two-option pill (EN / עב), active option filled with the brand
// accent gradient — matches the design brief's language toggle exactly,
// replacing the old single-button "switch to the other language" control.
export function LangToggle() {
  const { lang, setLang } = useLang();
  const options: { key: Lang; label: string }[] = [
    { key: "en", label: "EN" },
    { key: "he", label: "עב" },
  ];
  return (
    <div className="inline-flex gap-0.5 rounded-full border border-white/10 bg-white/5 p-0.5">
      {options.map((opt) => {
        const active = lang === opt.key;
        return (
          <button
            key={opt.key}
            type="button"
            onClick={() => setLang(opt.key)}
            aria-label={`Switch to ${opt.label}`}
            aria-pressed={active}
            className={
              active
                ? "rounded-full bg-[linear-gradient(135deg,var(--brand-accent),var(--brand-accent-2))] px-3 py-1 text-xs font-bold text-[#06121c]"
                : "rounded-full px-3 py-1 text-xs font-semibold text-white/60 transition hover:text-white"
            }
          >
            {opt.label}
          </button>
        );
      })}
    </div>
  );
}
