# Generated by Django 5.1.15 on 2026-07-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_game_sport_team_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=5)),
                ('summary', models.TextField()),
                ('key_factors', models.JSONField(default=list)),
                ('home_win_pct', models.PositiveSmallIntegerField()),
                ('away_win_pct', models.PositiveSmallIntegerField()),
                ('confidence', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_analyses', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'basketball match analyses',
                'constraints': [models.UniqueConstraint(fields=('game', 'language'), name='one_bball_analysis_per_game_language')],
            },
        ),
    ]
