# Generated by Django 5.1.15 on 2026-07-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=5)),
                ('summary', models.TextField()),
                ('key_factors', models.JSONField(default=list)),
                ('player1_win_pct', models.PositiveSmallIntegerField()),
                ('player2_win_pct', models.PositiveSmallIntegerField()),
                ('confidence', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='tennis.tennismatch')),
            ],
            options={
                'verbose_name_plural': 'tennis match analyses',
                'constraints': [models.UniqueConstraint(fields=('match', 'language'), name='one_tennis_analysis_per_match_language')],
            },
        ),
    ]
