import {
  ReactNode,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";

export type Lang = "en" | "he";

const translations = {
  en: {
    tagline: "Pick a sport. Get today's games and AI match analysis.",
    comingSoon: "Coming soon",
    sport_football: "Football",
    sport_basketball: "Basketball",
    sport_tennis: "Tennis",
    todaysGames: "Today's Games",
    loadingFixtures: "Loading fixtures...",
    noGames: "No games scheduled today.",
    loadErrorGames: "Couldn't load games",
    backToGames: "← Today's games",
    loadingMatch: "Loading match...",
    loadErrorGame: "Couldn't load game",
    aiAnalysis: "🤖 AI Match Analysis",
    analyzing: "The AI Agent is analyzing this match…",
    liveNow: "Live now",
    quarters: "Quarter by Quarter",
    form5: "Form (last 5)",
    winsAbbr: "W",
    drawsAbbr: "D",
    lossesAbbr: "L",
    scored: "scored",
    conceded: "conceded",
    lastGames: "last",
    lineups: "Starting Lineups",
    bench: "Bench",
    injuries: "Injuries & Suspensions",
    h2h: "Head to Head",
    noH2h: "No previous meetings on record.",
    draw: "Draw",
    confidence: "Confidence",
    generatedBy: "Generated by",
    confidence_low: "low",
    confidence_medium: "medium",
    confidence_high: "high",
    injury_out: "out",
    injury_doubtful: "doubtful",
    injury_suspended: "suspended",
  },
  he: {
    tagline: "בוחרים ענף ספורט, מקבלים את משחקי היום וניתוח AI לכל משחק.",
    comingSoon: "בקרוב",
    sport_football: "כדורגל",
    sport_basketball: "כדורסל",
    sport_tennis: "טניס",
    todaysGames: "משחקי היום",
    loadingFixtures: "טוען משחקים...",
    noGames: "אין משחקים מתוכננים היום.",
    loadErrorGames: "לא ניתן לטעון את המשחקים",
    backToGames: "→ משחקי היום",
    loadingMatch: "טוען משחק...",
    loadErrorGame: "לא ניתן לטעון את המשחק",
    aiAnalysis: "🤖 ניתוח AI למשחק",
    analyzing: "סוכן ה-AI מנתח את המשחק…",
    liveNow: "בשידור חי",
    quarters: "רבעים",
    form5: "כושר (5 אחרונים)",
    winsAbbr: "נ",
    drawsAbbr: "ת",
    lossesAbbr: "ה",
    scored: "שערי זכות",
    conceded: "שערי חובה",
    lastGames: "ב־",
    lineups: "הרכבים",
    bench: "ספסל",
    injuries: "פציעות והרחקות",
    h2h: "מפגשים קודמים",
    noH2h: "אין מפגשים קודמים.",
    draw: "תיקו",
    confidence: "רמת ביטחון",
    generatedBy: "נוצר על ידי",
    confidence_low: "נמוכה",
    confidence_medium: "בינונית",
    confidence_high: "גבוהה",
    injury_out: "לא ישחק",
    injury_doubtful: "מוטל בספק",
    injury_suspended: "מורחק",
  },
} as const;

export type TKey = keyof (typeof translations)["en"];

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TKey) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (key) => translations.en[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const stored = localStorage.getItem("lang");
    return stored === "he" ? "he" : "en";
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "he" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: TKey) => translations[lang][key] ?? translations.en[key];

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);

export function LangToggle() {
  const { lang, setLang } = useLang();
  return (
    <button
      className="lang-toggle"
      onClick={() => setLang(lang === "en" ? "he" : "en")}
      aria-label="Switch language"
    >
      {lang === "en" ? "עברית" : "English"}
    </button>
  );
}
