# Generated by Django 5.1.15 on 2026-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=200, unique=True)),
                ('translated_text', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['category', 'source_text'],
            },
        ),
    ]
