# Generated by Django 5.1.15 on 2026-07-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_factors', models.JSONField(default=list)),
                ('home_win_pct', models.PositiveSmallIntegerField()),
                ('draw_pct', models.PositiveSmallIntegerField()),
                ('away_win_pct', models.PositiveSmallIntegerField()),
                ('confidence', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'match analyses',
            },
        ),
    ]
