# Generated by Django 5.1.15 on 2026-07-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_agent', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchanalysis',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='matchanalysis',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='games.game'),
        ),
        migrations.AddConstraint(
            model_name='matchanalysis',
            constraint=models.UniqueConstraint(fields=('game', 'language'), name='one_analysis_per_game_language'),
        ),
    ]
